version: '3'

services:
    local_ssl_generator:
        build: "."
        container_name: "local_ssl_generator"
        restart: "no"
        stdin_open: true
        tty: true
        volumes:
            - "./etc/ssl:/etc/ssl/"
